Functions in Github

diff --git a/.github/workflows/context.yaml b/.github/workflows/context.yaml
--- a/.github/workflows/context.yaml
+++ b/.github/workflows/context.yaml
@@ -23,9 +23,15 @@ jobs:
     steps:
       - name: Dump GitHub context
         id: github_context_step
-        run: echo '${{ toJSON(github) }}'
+        run: |
+            echo '${{ toJSON(github) }}'
+            exit 1
       - name: Dump job context
-        run: echo '${{ toJSON(job) }}'
+        if:  failure() ## Runs next even if above step fails
+        run: |
+            echo '${{ toJSON(job) }}'
+            exit 1
+        continue-on-error: True ## Default False, Set to true runs all steps even if any step fails.
       - name: Dump steps context
         run: echo '${{ toJSON(steps) }}'
       - name: Dump runner context
@@ -37,4 +43,4 @@ jobs:
       - name: Dump env Variables
         run: echo '${{ toJSON(env) }}'
       - name: Retrieve job status
-        run: echo ${{job.dump_functions.status}}
+        run: echo '${{job.dump_functions.result}}''
